name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'  # Trigger on tags like v1.0, v2.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (optional but recommended for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build Docker image and tag with commit hash and version (if available)
    - name: Build and tag Docker image
      run: |
        REPO_NAME="${{ github.repository }}"
        REPO_NAME_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')

        IMAGE_NAME="ghcr.io/$REPO_NAME_LOWERCASE/my-image"
        COMMIT_SHA=$(git rev-parse --short HEAD)
        
        # If the commit is tagged, use the tag as the version
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        else
          TAG="latest"
        fi

        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV

        # Build the image using Buildx
        docker build \
          --tag $IMAGE_NAME:$COMMIT_SHA \
          --tag $IMAGE_NAME:$TAG .


    # Push the Docker image to Docker Hub or GHCR
    - name: Push Docker image
      run: |
        echo "IMAGE_NAME=$IMAGE_NAME"
        echo "COMMIT_SHA=$COMMIT_SHA"
        echo "TAG=$TAG"

        docker push $IMAGE_NAME:$COMMIT_SHA
        docker push $IMAGE_NAME:$TAG
