name: Build and Push Docker Image

on:
  # Trigger on pull request to the `main` branch
  pull_request:
    branches:
      - main

  # Trigger on release events (e.g., creating or publishing a release)
  release:
    types:
      - created
      - published

  # Trigger on push to any branch
  push:
    branches:
      - '**'  # Wildcard to match any branch
    tags:
      - '*'  # Wildcard to match any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (optional but recommended for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build Docker image and tag with commit hash and version (if available)
    - name: Build and tag Docker image
      run: |
        REPO_NAME="${{ github.repository }}"
        REPO_NAME_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')

        IMAGE_NAME="ghcr.io/$REPO_NAME_LOWERCASE/my-image"
        COMMIT_SHA=$(git rev-parse --short HEAD)
        

        # If the commit is tagged, use the tag as the version
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        elif [[ $GITHUB_REF == refs/heads/main ]]; then
          TAG="latest"
        else
          TAG=""
        fi


        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV


        # Build the image for the commit sha
        if [[ $TAG == ""]]; then
          docker build \
            --tag $IMAGE_NAME:$COMMIT_SHA \
            --tag $IMAGE_NAME:$TAG \
            --push $IMAGE_NAME:$COMMIT_SHA \
            .
        else
          docker build \
          --tag $IMAGE_NAME:$COMMIT_SHA \
          --tag $IMAGE_NAME:$TAG \
          --push $IMAGE_NAME:$COMMIT_SHA \
          .
        fi

    # # Create and push the image to GHCR
    # - name: Create and push tag if branch is main
    #   if: github.ref == 'refs/heads/main'  # Only run this step if the branch is main
    #   # set the tag to latest
    #   run: |
    #     echo "you are on the main branch"

    # # Push the Docker image to Docker Hub or GHCR
    # - name: Push Docker image
    #   run: |
    #     echo "IMAGE_NAME=$IMAGE_NAME"
    #     echo "COMMIT_SHA=$COMMIT_SHA"
    #     echo "TAG=$TAG"

    #     docker push $IMAGE_NAME:$COMMIT_SHA
    #     docker push $IMAGE_NAME:$TAG
